#!/bin/sh

echo "Running spotless check..."

files=$(git diff --name-only --staged)

./gradlew spotlessApply
status=$?

if [ $status -ne 0 ]; then
  exit 1
fi

for file in $files; do
  git add $file
done

exit 0